name: Docker Image Cardano Node
on:
  workflow_dispatch:
  push:
    paths:
      - 'Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: |
        docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}  
    - name: Dockerfile Download
      run: |
        curl -sLo Dockerstage3 https://raw.githubusercontent.com/stakelovelace/cardano-node/master/Dockerfile
    - name: Compiling new node software
      run: |      
        docker build . --file Dockerstage3 --compress --tag stakelovelace/cardano-node:latest
    - name: Docker push
      run: |
        docker push stakelovelace/cardano-node:latest
    - name: Install Docker Scout
      run: |
        curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
        sh install-scout.sh
    - name: Docker Scout
      run: |
        docker scan stakelovelace/cardano-node:latest
    - name: Handle Docker Scout results
      run: |
        # Run Docker Scout and save the output to a file
        docker scout quickview stakelovelace/cardano-node:latest -o docker_scout_results.txt

        # Read the Docker Scout results file
        result=$(cat docker_scout_results.txt)

        # Publish the results as a GitHub issue
        echo "$result" | gh issue create --title "Docker Scout Results" --body -

        # Push the results to a Docker Hub repository description
        repository="stakelovelace/cardano-node"
        username="${{ secrets.DOCKER_USERNAME }}"
        password="${{ secrets.DOCKER_PASSWORD }}"

        echo "$result" | docker login -u "$username" --password-stdin
        docker run --rm -v "$PWD:/workspace" docker/compose:1.29.2 sh -c "echo '$result' > /workspace/scan_results.txt"
        docker push "$repository"
